# Generated by Django 3.2.6 on 2021-08-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item_id',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.PositiveIntegerField(blank=True, max_length=100000, null=True),
        ),
    ]
