# Generated by Django 3.2.6 on 2021-08-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210831_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(blank=True, max_length=10000, null=True),
        ),
    ]
