# Generated by Django 3.2.6 on 2021-09-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('profession', models.CharField(choices=[('Backend Developer', 'BACKEND DEVELOPER'), ('IT-Admin', 'IT-ADMIN'), ('Sales Representative', 'SALES REPRESENTATIVE'), ('Support', 'SUPPORT'), ('DevOps Engineer', 'DEVOPS ENGINEER'), ('Frontend developer', 'FRONTEND DEVELOPER'), ('Human Resources', 'HUMAN RESOURCES')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
